data:
    name: 'patches_dataset'
    alteration: 'all'
    cache_in_memory: false
    validation_size: 100
    preprocessing:
        resize: False
model:
    name: 'classical_detectors'
    method: 'harris'  # 'shi' 'fast'
    batch_size: 50  # unused
    learning_rate: 0.001  # unused
    nms: 4
    top_k: 300
eval_iter: 500
seed: 1
