data:
    name: 'hpatches'
    primitives: 'all'
    cache_in_memory: false
    validation_size: 100
model:
    name: 'classical_detectors'
    method: 'harris'  # 'shi' 'fast'
    batch_size: 50  # unused
    learning_rate: 0.001  # unused
eval_iter: 500
seed: 1