data:
    name: 'coco'
    labels: 'outputs/magic-point_synth-120-160_noise-motion_coco_homography-1_num-100_fcnt-4'
    cache_in_memory: true
    validation_size: 192
    augmentations:
        enable: false
        primitives: [
            'random_brightness',
            'random_contrast',
            'motion_blur',
            'additive_gaussian_noise',
            'additive_speckle_noise',
            'add_shade']
        params:
            random_brightness: {max_change: 40}
            random_contrast: {max_change: [0.5, 1.5]}
            motion_blur: {ksize: 3}
            additive_gaussian_noise: {std: [0, 8]}
            additive_speckle_noise: {intensity: 1}
            add_shade: {amplitude: [-.5, .5], kernel_size_interval: [100, 150]}
model:
    name: 'magic_point'
    batch_size: 32
    eval_batch_size: 32
    learning_rate: 0.001
    detection_threshold: 0.015 # 1/65
    nms: 4
    top_k: 300
train_iter: 500000
validation_interval: 1000
