data:
    name: 'coco'
    cache_in_memory: false
    validation_size: 100
model:
    name: 'magic_point'
    batch_size: 50
    eval_batch_size: 50
    learning_rate: 0.001
    detection_threshold: 0.015 # 1/65
    nms: 4
    top_k: 300
    homography_adaptation:
        num: 1000
        aggregation: 'sum'
        filter_counts: 4
        homographies:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.1
            perspective_amplitude: 0.05
eval_iter: -1
