data:
    name: 'coco'
    primitives: 'all'
    cache_in_memory: false
    validation_size: 100
    augmentations:
        enable: true
        primitives: [
            'additive_gaussian_noise',
            'motion_blur',
            'additive_speckle_noise',
            'add_shade',
            'random_brightness',
            'random_contrast',
            'elastic_transform'],
        params:
            motion_blur: {ksize: 7},
            additive_gaussian_noise: {std: [3, 5]},
            additive_speckle_noise: {intensity: 1},
            random_brightness: {max_change: 50},
            random_contrast: {max_change: [0.5, 1.7]},
            add_shade: {transparency: 0.4},
            elastic_transform:
                sigma_params: [0.05, 0.05]
                alpha_params: [0.5, 0.5]
                padding: 2
model:
    name: 'magic_point'
    batch_size: 50
    eval_batch_size: 50
    learning_rate: 0.001
    detection_threshold: 0.015 # 1/65
    nms: 4
    top_k: 300
    homography_adaptation:
        num: 100
        aggregation: 'sum'
        filter_counts: 4
        homographies:
            translation: true
            rotation: true
            scaling: true
            perspective: true
            scaling_amplitude: 0.1
            perspective_amplitude: 0.05
train_iter: 100000
eval_iter: -1
