data:
    name: 'coco'
    primitives: 'all'
    cache_in_memory: false
    validation_size: 100
model:
    name: 'magic_point'
    batch_size: 50
    eval_batch_size: 50
    learning_rate: 0.001
    detection_threshold: 0.3
train_iter: 100000
eval_iter: 50
