data:
    name: 'synthetic_shapes'
    image_size: [240, 320]
    primitive: 'all'
model:
    name: 'magic_point'
    batch_size: 50
    eval_batch_size: 100
    learning_rate: 0.001
train_iter: 1000
