data:
    name: 'coco'
    primitives: 'all'
    cache_in_memory: false
    validation_size: 100
model:
    name: 'super_point'
    batch_size: 32
    eval_batch_size: 32
    learning_rate: 0.001
    detection_threshold: 0.4
    lambda_d: 250
    positive_margin: 1
    negative_margin: 0.2
    lambda_loss: 0.0001
train_iter: 100000
eval_iter: 50
